local root = lv_scr_act()
lv_obj_clean(root)
lv_obj_set_style_bg_color(root, 0x10161d)
lv_obj_set_style_text_color(root, 0xf8fafc)

local title = lv_label_create(root)
lv_label_set_text(title, "Power Stage")
lv_obj_set_style_text_color(title, 0x67e8f9)
lv_obj_set_width(title, 330)
lv_obj_align(title, LV_ALIGN_TOP_LEFT, 30, 34)

local subtitle = lv_label_create(root)
lv_label_set_text(subtitle, "VBAT + AW32001 Runtime App API")
lv_obj_set_style_text_color(subtitle, 0xcbd5e1)
lv_obj_set_width(subtitle, 330)
lv_obj_align(subtitle, LV_ALIGN_TOP_LEFT, 30, 72)

local battery = lv_label_create(root)
lv_label_set_text(battery, "Battery --mV")
lv_obj_set_style_text_color(battery, 0xfbbf24)
lv_obj_set_width(battery, 330)
lv_obj_align(battery, LV_ALIGN_TOP_LEFT, 30, 140)
vibe_power_label(battery, "battery")

local charger = lv_label_create(root)
lv_label_set_text(charger, "Charger --")
lv_obj_set_style_text_color(charger, 0x93c5fd)
lv_obj_set_width(charger, 330)
lv_obj_align(charger, LV_ALIGN_TOP_LEFT, 30, 188)
vibe_power_label(charger, "charger")

local hint = lv_label_create(root)
lv_label_set_text(hint, "Manifest refreshes power.battery + power.charger")
lv_obj_set_style_text_color(hint, 0xc4b5fd)
lv_obj_set_width(hint, 330)
lv_obj_align(hint, LV_ALIGN_TOP_LEFT, 30, 246)

local tick = lv_label_create(root)
lv_label_set_text(tick, "Power Tick 0")
lv_obj_set_style_text_color(tick, 0xfda4af)
lv_obj_align(tick, LV_ALIGN_BOTTOM_LEFT, 30, -32)
vibe_timer_label(tick, 1000, "Power Tick")

print("[power_stage] runtime power stage requested")
