from building import *

cwd = GetCurrentDir()
objs = []

if GetDepend('PKG_USING_LITTLEVGL2RTT'):
    objs = Glob('*.c')
    group = DefineGroup('App_Board_Diagnostics', objs, depend=['PKG_USING_LITTLEVGL2RTT'], CPPPATH=[''], LOCAL_CCFLAGS='')

Return('objs')
