local root = lv_scr_act()
lv_obj_clean(root)
lv_obj_set_style_bg_color(root, 0x0a1623)
lv_obj_set_style_text_color(root, 0xf8fafc)

local title = lv_label_create(root)
lv_label_set_text(title, "Touch Stage")
lv_obj_set_style_text_color(title, 0x67e8f9)
lv_obj_set_width(title, 330)
lv_obj_align(title, LV_ALIGN_TOP_LEFT, 30, 34)

local subtitle = lv_label_create(root)
lv_label_set_text(subtitle, "Runtime touch state with gesture and hold data")
lv_obj_set_style_text_color(subtitle, 0xcbd5e1)
lv_obj_set_width(subtitle, 330)
lv_obj_align(subtitle, LV_ALIGN_TOP_LEFT, 30, 72)

local count = lv_label_create(root)
lv_label_set_text(count, "Touch 0")
lv_obj_set_style_text_color(count, 0xfbbf24)
lv_obj_set_width(count, 330)
lv_obj_align(count, LV_ALIGN_TOP_LEFT, 30, 132)
vibe_touch_label(count, "count")

local point = lv_label_create(root)
lv_label_set_text(point, "Touch --")
lv_obj_set_style_text_color(point, 0x93c5fd)
lv_obj_set_width(point, 330)
lv_obj_align(point, LV_ALIGN_TOP_LEFT, 30, 176)
vibe_touch_label(point, "last")

local gesture = lv_label_create(root)
lv_label_set_text(gesture, "none")
lv_obj_set_style_text_color(gesture, 0x86efac)
lv_obj_set_width(gesture, 330)
lv_obj_align(gesture, LV_ALIGN_TOP_LEFT, 30, 220)
vibe_touch_label(gesture, "gesture")

local delta = lv_label_create(root)
lv_label_set_text(delta, "0,0")
lv_obj_set_style_text_color(delta, 0xf9a8d4)
lv_obj_set_width(delta, 330)
lv_obj_align(delta, LV_ALIGN_TOP_LEFT, 30, 264)
vibe_touch_label(delta, "delta")

local duration = lv_label_create(root)
lv_label_set_text(duration, "0ms")
lv_obj_set_style_text_color(duration, 0xfca5a5)
lv_obj_set_width(duration, 330)
lv_obj_align(duration, LV_ALIGN_TOP_LEFT, 30, 308)
vibe_touch_label(duration, "duration")

local active = lv_label_create(root)
lv_label_set_text(active, "idle")
lv_obj_set_style_text_color(active, 0xc4b5fd)
lv_obj_set_width(active, 330)
lv_obj_align(active, LV_ALIGN_BOTTOM_LEFT, 30, -62)
vibe_touch_label(active, "active")

local tick = lv_label_create(root)
lv_label_set_text(tick, "Touch Tick 0")
lv_obj_set_style_text_color(tick, 0xfda4af)
lv_obj_align(tick, LV_ALIGN_BOTTOM_LEFT, 30, -28)
vibe_timer_label(tick, 1000, "Touch Tick")

print("[touch_stage] runtime touch stage requested")
