local root = lv_scr_act()
lv_obj_clean(root)
lv_obj_set_style_bg_color(root, 0x08111b)
lv_obj_set_style_text_color(root, 0xf8fafc)

local title = lv_label_create(root)
lv_label_set_text(title, "GPIO Keys Stage")
lv_obj_set_style_text_color(title, 0x67e8f9)
lv_obj_set_width(title, 330)
lv_obj_align(title, LV_ALIGN_TOP_LEFT, 30, 34)

local subtitle = lv_label_create(root)
lv_label_set_text(subtitle, "Runtime whitelist GPIO view for KEY1 / KEY2")
lv_obj_set_style_text_color(subtitle, 0xcbd5e1)
lv_obj_set_width(subtitle, 330)
lv_obj_align(subtitle, LV_ALIGN_TOP_LEFT, 30, 72)

local key1 = lv_label_create(root)
lv_label_set_text(key1, "KEY1 --")
lv_obj_set_style_text_color(key1, 0xfbbf24)
lv_obj_set_width(key1, 330)
lv_obj_align(key1, LV_ALIGN_TOP_LEFT, 30, 148)
vibe_gpio_label(key1, "key1")

local key1_level = lv_label_create(root)
lv_label_set_text(key1_level, "KEY1 level --")
lv_obj_set_style_text_color(key1_level, 0x93c5fd)
lv_obj_set_width(key1_level, 330)
lv_obj_align(key1_level, LV_ALIGN_TOP_LEFT, 30, 192)
vibe_gpio_label(key1_level, "key1.level")

local key2 = lv_label_create(root)
lv_label_set_text(key2, "KEY2 --")
lv_obj_set_style_text_color(key2, 0x86efac)
lv_obj_set_width(key2, 330)
lv_obj_align(key2, LV_ALIGN_TOP_LEFT, 30, 248)
vibe_gpio_label(key2, "key2")

local key2_level = lv_label_create(root)
lv_label_set_text(key2_level, "KEY2 level --")
lv_obj_set_style_text_color(key2_level, 0xf9a8d4)
lv_obj_set_width(key2_level, 330)
lv_obj_align(key2_level, LV_ALIGN_TOP_LEFT, 30, 292)
vibe_gpio_label(key2_level, "key2.level")

local hint = lv_label_create(root)
lv_label_set_text(hint, "Press board keys to watch pressed/level change")
lv_obj_set_style_text_color(hint, 0xc4b5fd)
lv_obj_set_width(hint, 330)
lv_obj_align(hint, LV_ALIGN_BOTTOM_LEFT, 30, -62)

local tick = lv_label_create(root)
lv_label_set_text(tick, "GPIO Tick 0")
lv_obj_set_style_text_color(tick, 0xfda4af)
lv_obj_align(tick, LV_ALIGN_BOTTOM_LEFT, 30, -28)
vibe_timer_label(tick, 1000, "GPIO Tick")

print("[gpio_keys_stage] runtime gpio stage requested")
