local root = lv_scr_act()
lv_obj_clean(root)
lv_obj_set_style_bg_color(root, 0x0b1f2a)
lv_obj_set_style_text_color(root, 0xf8fafc)

local title = lv_label_create(root)
lv_label_set_text(title, "Sensor Stage")
lv_obj_set_style_text_color(title, 0x67e8f9)
lv_obj_set_width(title, 330)
lv_obj_align(title, LV_ALIGN_TOP_LEFT, 30, 34)

local subtitle = lv_label_create(root)
lv_label_set_text(subtitle, "Board signals, live and calm")
lv_obj_set_style_text_color(subtitle, 0xcbd5e1)
lv_obj_set_width(subtitle, 330)
lv_obj_align(subtitle, LV_ALIGN_TOP_LEFT, 30, 72)

local light = lv_label_create(root)
lv_label_set_text(light, "Light --")
lv_obj_set_style_text_color(light, 0xfbbf24)
lv_obj_set_width(light, 330)
lv_obj_align(light, LV_ALIGN_TOP_LEFT, 30, 126)
vibe_sensor_label(light, "light")

local acce = lv_label_create(root)
lv_label_set_text(acce, "Motion --")
lv_obj_set_style_text_color(acce, 0x93c5fd)
lv_obj_set_width(acce, 340)
lv_obj_align(acce, LV_ALIGN_TOP_LEFT, 30, 174)
vibe_sensor_label(acce, "acce")

local step = lv_label_create(root)
lv_label_set_text(step, "Steps --")
lv_obj_set_style_text_color(step, 0x86efac)
lv_obj_set_width(step, 330)
lv_obj_align(step, LV_ALIGN_TOP_LEFT, 30, 222)
vibe_sensor_label(step, "step")

local tick = lv_label_create(root)
lv_label_set_text(tick, "Stage Tick 0")
lv_obj_set_style_text_color(tick, 0xfda4af)
lv_obj_align(tick, LV_ALIGN_BOTTOM_LEFT, 30, -34)
vibe_timer_label(tick, 1000, "Stage Tick")

print("[sensor_stage] live sensor stage requested")
