local root = lv_scr_act()
lv_obj_clean(root)
lv_obj_set_style_bg_color(root, 0x101820)
lv_obj_set_style_text_color(root, 0xf8fafc)

local title = lv_label_create(root)
lv_label_set_text(title, "Sensor Dashboard")
lv_obj_set_style_text_color(title, 0x5eead4)
lv_obj_set_width(title, 330)
lv_obj_align(title, LV_ALIGN_TOP_LEFT, 30, 38)

local light = lv_label_create(root)
lv_label_set_text(light, "Light --")
lv_obj_set_style_text_color(light, 0xfbbf24)
lv_obj_set_width(light, 330)
lv_obj_align(light, LV_ALIGN_TOP_LEFT, 30, 94)
vibe_sensor_label(light, "light")

local acce = lv_label_create(root)
lv_label_set_text(acce, "Acce --")
lv_obj_set_style_text_color(acce, 0x93c5fd)
lv_obj_set_width(acce, 340)
lv_obj_align(acce, LV_ALIGN_TOP_LEFT, 30, 140)
vibe_sensor_label(acce, "acce")

local gyro = lv_label_create(root)
lv_label_set_text(gyro, "Gyro --")
lv_obj_set_style_text_color(gyro, 0xc4b5fd)
lv_obj_set_width(gyro, 340)
lv_obj_align(gyro, LV_ALIGN_TOP_LEFT, 30, 186)
vibe_sensor_label(gyro, "gyro")

local mag = lv_label_create(root)
lv_label_set_text(mag, "Mag --")
lv_obj_set_style_text_color(mag, 0x86efac)
lv_obj_set_width(mag, 340)
lv_obj_align(mag, LV_ALIGN_TOP_LEFT, 30, 232)
vibe_sensor_label(mag, "mag")

local step = lv_label_create(root)
lv_label_set_text(step, "Step --")
lv_obj_set_style_text_color(step, 0xfda4af)
lv_obj_set_width(step, 330)
lv_obj_align(step, LV_ALIGN_TOP_LEFT, 30, 278)
vibe_sensor_label(step, "step")

local tick = lv_label_create(root)
lv_label_set_text(tick, "Sensor Tick 0")
lv_obj_set_style_text_color(tick, 0xcbd5e1)
lv_obj_align(tick, LV_ALIGN_BOTTOM_LEFT, 30, -32)
vibe_timer_label(tick, 1000, "Sensor Tick")

print("[sensor_dash] sensor snapshot labels requested")
