Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

cwd = GetCurrentDir()
src = ['main.c']

if GetDepend('BSP_BLE_SIBLES') and os.path.exists(os.path.join(cwd, 'ble_app.c')):
    src+=['ble_app.c']

if GetDepend('BSP_BT_APP') and os.path.exists(os.path.join(cwd, 'bt_app.c')):
    src+=['bt_app.c']


CPPPATH = [cwd]

group = DefineGroup('App_utils', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
